### ISSUE TITLE
{$NGINX_HTTP_PORT}]" became not supported: Received value [] is not suitable for value type [Numeric (unsigned)] and data type [Decimal]

### ISSUE THREAD

**Issue by ssoltane** [breuninger-ecom/zabbix-agent-extensions#2]
Hi,
Fisrt of all thks for the extension. I m having troubles making the nginx monitoring work.
I added {$NGINX_HTTP_PORT} =80 to my host macro but i'm getting this error.
Thks in advance for your help

**Comment by chrw** [comment]
What is the link to your NGINX status page? The default is http://127.0.0.1:80/basic_status afaik

**Comment by scoopex** [comment]
Improved documentation, see https://nginx.org/en/docs/http/ngx_http_stub_status_module.html
